version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'

    - package-ecosystem: 'npm'
      directory: '/templates/authentication-typescript'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'

    - package-ecosystem: 'npm'
      directory: '/templates/blank-typescript'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'

    - package-ecosystem: 'npm'
      directory: '/templates/routing-typescript'
      schedule:
          interval: 'monthly'
          day: 'monday'
      open-pull-requests-limit: 1
      target-branch: 'dev'
      labels:
          - 'external-dependency'
