name: Build

on:
    push:
        branches: ['dev', 'master']
    pull_request:
        branches: ['dev', 'master']
    pull_request_target:
        types:
            - opened
        branches:
            - '*/*'

permissions:
    pull-requests: write
    contents: read

jobs:
    prettier_lint_blank:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn
              working-directory: templates/blank-typescript
            - run: yarn prettier:check
              working-directory: templates/blank-typescript
            - run: yarn lint
              working-directory: templates/blank-typescript

    prettier_lint_routing:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn
              working-directory: templates/routing-typescript
            - run: yarn prettier:check
              working-directory: templates/routing-typescript
            - run: yarn lint
              working-directory: templates/routing-typescript

    unit_test_blank:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn
              working-directory: templates/blank-typescript
            - run: yarn test
              working-directory: templates/blank-typescript

    unit_test_routing:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn
              working-directory: templates/blank-typescript
            - run: yarn test
              working-directory: templates/blank-typescript

    publish_cli_templates:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') }}
        needs: [prettier_lint_blank, prettier_lint_routing, unit_test_blank, unit_test_routing]
        strategy:
            matrix:
                node-version: [20.x]
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn --immutable
            - run: npm run publish:package -- -b ${{env.BRANCH}}
    