name: Build

on:
    push:
        branches: ['dev', 'master']
    pull_request:
        branches: ['dev', 'master']
    pull_request_target:
        types:
            - opened
        branches:
            - '*/*'

permissions:
    pull-requests: write
    contents: read

jobs:
    prettier_templates:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn 
            - run: yarn prettier:check

    lint_templates:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                node-version: [20.x]
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn lint

    unit_test_templates:
        runs-on: ubuntu-latest
      
        strategy:
            matrix:
                node-version: [20.x]
      
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn
            - run: yarn
              working-directory: templates/authentication-typescript
            - run: yarn test
              working-directory: templates/authentication-typescript
            - run: yarn
              working-directory: templates/blank-typescript
            - run: yarn test
              working-directory: templates/blank-typescript
            - run: yarn
              working-directory: templates/routing-typescript
            - run: yarn test
              working-directory: templates/routing-typescript

      build_templates:
          runs-on: ubuntu-latest
          needs: [prettier_templates, lint_templates, unit_test_templates]
              
          strategy:
              matrix:
                  node-version: [20.x]
              
          steps:
              - uses: actions/checkout@v4
              - name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'yarn'
              - run: yarn
              - run: yarn
                working-directory: templates/authentication-typescript
              - run: yarn build
                working-directory: templates/authentication-typescript
              - run: yarn
                working-directory: templates/blank-typescript
              - run: yarn build
                working-directory: templates/blank-typescript
              - run: yarn
                working-directory: templates/routing-typescript
              - run: yarn build
                working-directory: templates/routing-typescript


    publish_cli_templates:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') }}
        needs: [prettier_templates, lint_templates, unit_test_templates, build_templates]
        strategy:
            matrix:
                node-version: [20.x]
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            BRANCH: ${{ github.ref == 'refs/heads/master' && 'master' || 'dev' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn --immutable
            - run: npm run publish:package -- -b ${{env.BRANCH}}
    